### ISSUE TITLE
사이즈 수정

### ISSUE THREAD

**Issue by soi-ha** [UMC-DRAWMAP/DRAWMAP-FE#20]
- [x] header
- [x] footer
- [x] ChallengeRowBox
- [x] SmallBox
- [x] ChallengeColumnBox
- [x] ArchiveBox
- [x] Button

**Comment by jungwoo3490** [comment]
Footer 수정 완료, ChallengeColumnBox 추가 수정 필요

**Comment by jungwoo3490** [comment]
ChallengeColumnBox, ArchiveBox 사이즈 수정 완료
